const quizData = [
  {
    question: "What is the most used programming language in 2019?",
    a: "Java",
    b: "C",
    c: "Python",
    d: "JavaScript",
    correct: "d",
  },
  {
    question: "Who is the President of US?",
    a: "Florin Pop",
    b: "Donald Trump",
    c: "Ivan Saldano",
    d: "Mihai Andrei",
    correct: "b",
  },
  {
    question: "What does HTML stand for?",
    a: "Hypertext Markup Language",
    b: "Cascading Style Sheet",
    c: "Jason Object Notation",
    d: "Helicopters Terminals Motorboats Lamborginis",
    correct: "a",
  },
  {
    question: "What year was JavaScript launched?",
    a: "1996",
    b: "1995",
    c: "1994",
    d: "none of the above",
    correct: "b",
  },
  {
    question: "What does CSS stand for?",
    a: "Computer Style Sheets",
    b: "Cascading Style Sheets",
    c: "Colorful Style Sheets",
    d: "Creative Style Sheets",
    correct: "b",
  },
  {
    question: "Which company developed the Java programming language?",
    a: "Sun Microsystems",
    b: "Microsoft",
    c: "Google",
    d: "Apple",
    correct: "a",
  },
  {
    question: "What does SQL stand for?",
    a: "Structured Query Language",
    b: "Strong Question Language",
    c: "Structured Query Level",
    d: "Simple Query Language",
    correct: "a",
  },
  {
    question: "Which language is primarily used for iOS app development?",
    a: "Java",
    b: "Swift",
    c: "Python",
    d: "C#",
    correct: "b",
  },
  {
    question: "Who created the Linux operating system?",
    a: "Bill Gates",
    b: "Steve Jobs",
    c: "Linus Torvalds",
    d: "Mark Zuckerberg",
    correct: "c",
  },
  {
    question:
      "Which protocol is used to secure communication over the Internet?",
    a: "HTTP",
    b: "FTP",
    c: "SMTP",
    d: "HTTPS",
    correct: "d",
  },
  {
    question: "What does JSON stand for?",
    a: "JavaScript Object Notation",
    b: "Java Source Open Network",
    c: "JavaScript Oriented Notation",
    d: "Java Standard Object Notation",
    correct: "a",
  },
  {
    question:
      "What is the primary language recommended for Android app development?",
    a: "Java",
    b: "Swift",
    c: "Kotlin",
    d: "Python",
    correct: "c",
  },
  {
    question: "Which company developed the React library?",
    a: "Google",
    b: "Facebook",
    c: "Microsoft",
    d: "Twitter",
    correct: "b",
  },
  {
    question: "What is the purpose of a function in programming?",
    a: "To store data",
    b: "To perform a specific task",
    c: "To style web pages",
    d: "To create graphics",
    correct: "b",
  },
];

export default quizData;